apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ghantt
  namespace: go-ghantt
  labels:
    app: go-ghantt
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - go-ghantt.mlinarik.com
    secretName: go-ghantt-tls
  rules:
  - host: go-ghantt.mlinarik.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-ghantt
            port:
              number: 8080
